export const actions = {
  ADD_COUNTER: "ADD_COUNTER",
  REST_COUNTER: "REST_COUNTER",
  ADD_2_COUNTER: "ADD_2_COUNTER",
  GET_MOVIES_REQUEST: "GET_MOVIES_REQUEST",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAIL: "GET_MOVIES_FAIL",
};
